// Which glossary entry (src/data/glossary.json) explains which table row, keyed by export name or
// "name.field". Rows listed here show the glossary definition as their tooltip, the same one as in the text;
// Table.astro checks every name at build time, so a typo fails the build.
export const GLOSSARY_TERMS = {
    julianDayUT: "Julian Day",
    julianEphemerisDay: "Delta T",
    deltaT: "Delta T",
    siderealTime: "Sidereal time",
    apparentSiderealTime: "Sidereal time",
    atmosphericRefraction: "Atmospheric refraction",
    atmosphericRefractionFromApparent: "Atmospheric refraction",
    orbitEccentricity: "Orbital eccentricity",
    longitudeNutation: "Nutation",
    obliquityNutation: "Nutation",
    meanObliquity: "Obliquity of the ecliptic",
    trueObliquity: "Obliquity of the ecliptic",
    meanAnomaly: "Mean anomaly",
    meanLongitude: "Mean longitude",
    equationOfCenter: "Equation of the center",
    trueAnomaly: "True anomaly",
    trueLongitude: "True longitude",
    apparentLongitude: "Apparent position",
    apparentPosition: "Apparent position",
    equatorialHorizontalParallax: "Parallax",
    topocentricPosition: "Parallax",
    horizontalPosition: "Horizontal coordinates",
    apparentAngularDiameter: "Apparent angular diameter",
    topocentricAngularDiameter: "Apparent angular diameter",
    "solar.magnitude": "Eclipse magnitude",
    "lunar.umbralMagnitude": "Eclipse magnitude",
    "lunar.penumbralMagnitude": "Eclipse magnitude",
    meanElongation: "Mean elongation",
    meanArgumentOfLatitude: "Argument of latitude",
    meanAscendingNodeLongitude: "Longitude of the ascending node",
    position: "Ecliptic coordinates",
    opticalLibrations: "Libration",
    librations: "Libration",
    parallacticAngle: "Parallactic angle",
    positionAngleOfAxis: "Position angle of axis",
    phaseAngle: "Phase angle",
    illuminatedFraction: "Illuminated fraction",
    earthshine: "Earthshine",
    "solar.phase": "Eclipse phase",
    "solar.positionAngle": "Position angle",
    "lunar.phase": "Eclipse phase",
    "lunar.positionAngle": "Position angle",
    horizonDip: "Horizon dip",
    "lunar.umbraRadiusKm": "Umbra",
    "lunar.penumbraRadiusKm": "Penumbra",
};
